[package]
name = "shaft-corelib"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
boa_engine = "0.21.0"
cu = { workspace = true, features = ["process", "json", "derive", "prompt"] }
enumset.workspace = true
fs2 = "0.4.3"
fxhash = "0.2.1"
reqwest = { version = "0.13.1", features = ["blocking", "gzip"] }
serde = "1"
sha2 = "0.10.9"
shell-words.workspace = true
sysinfo = "0.38.0"
tokio = "1"
flate2.workspace = true
tar.workspace = true
zip.workspace = true
shaftim-build = { path = "../tools/shaftim-build", default-features = false }

[target.'cfg(windows)'.dependencies]
win-envedit.workspace = true
winapi = { version = "0.3.9", features = ["securitybaseapi", "processthreadsapi", "impl-default"] }

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[build-dependencies]
cu = { workspace = true, features = [ "fs", "toml" ] }
flate2.workspace = true
ignore.workspace = true
tar.workspace = true
