[package]
name = "drillshaft-env"
version = "0.0.0"
edition = "2024"

[dependencies]
cu = { workspace = true, features = ["print", "process", "json"] }
enumset.workspace = true
serde = "1"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
