[package]
name = "shaftim"
version = "0.0.0"
description = "building a wrapper binary for executing a command"
edition = "2024"
publish = false

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Console"] }
shell-words.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[build-dependencies]
shaftim-build = { path = "../shaftim-build", default-features = false, features = ["build"] }
cu = { workspace = true, features = [ "fs" ] }

[lib]
path = "lib.rs"

[[bin]]
path = "main.rs"
name = "shaftim"
