# [build]
# rustflags = ["-Zlocation-detail=none", "-Zfmt-debug=none", "-Zunstable-options", "-Cpanic=immediate-abort"]

[env]
SHAFT_SHIM_BUILD_CONFIG = "config.json" # default config, for testing
